// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm5Bx4OAY0DCQOkRBwKcRy3bTyAWj11o8',
    appId: '1:1028935472034:web:224a5f5ce7e2284069d8fb',
    messagingSenderId: '1028935472034',
    projectId: 'flutterchatapp-5e181',
    authDomain: 'flutterchatapp-5e181.firebaseapp.com',
    storageBucket: 'flutterchatapp-5e181.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPqAY5Ou1G0Dte-iGwvfo3t-SLN40aPYc',
    appId: '1:1028935472034:android:5b5d1baaac561fe269d8fb',
    messagingSenderId: '1028935472034',
    projectId: 'flutterchatapp-5e181',
    storageBucket: 'flutterchatapp-5e181.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9mlQz_xX2pQhCmypGqEGrYG9s9VBBJlw',
    appId: '1:1028935472034:ios:a03d77ab941d117569d8fb',
    messagingSenderId: '1028935472034',
    projectId: 'flutterchatapp-5e181',
    storageBucket: 'flutterchatapp-5e181.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9mlQz_xX2pQhCmypGqEGrYG9s9VBBJlw',
    appId: '1:1028935472034:ios:6f51f2777109398069d8fb',
    messagingSenderId: '1028935472034',
    projectId: 'flutterchatapp-5e181',
    storageBucket: 'flutterchatapp-5e181.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
